# Generated by Django 6.0 on 2025-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.CharField(max_length=36)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x73a561ce27a0>', max_length=36, primary_key=True, serialize=False),
        ),
    ]
